WRR-1005: Updated Eslint to version 9
enactjs/dev-utils pull request #140
Opened 2024-11-28 12:48 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] I have run automated CLI testing and it is passed
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Support for eslint 8 was dropped and Eslint 9 was released

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update Eslint to version 9 and eslint related modules to latest versions
Adopted flat config

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
Eslint 9 requires minimum node 18.18 https://eslint.org/docs/latest/use/migrate-to-9.0.0#-nodejs--v1818-v19-are-no-longer-supported 

### Links
[//]: # (Related issues, references)
WRR-1005

### Comments
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)

2024-11-29 14:38 UTC, stanca-pop-lgp requested changes

2024-11-29 14:38 UTC, stanca-pop-lgp commented on CHANGELOG.md
> +* Updated ESLint to `9.1.5` including updating eslint related modules
```suggestion
* Updated ESLint to `9.1.5` including eslint related modules.
```

2024-12-03 07:46 UTC, stanca-pop-lgp approved these changes

2025-02-20 01:59 UTC, hong6316 approved these changes
👍

2025-02-20 01:59 UTC, merged